### ISSUE TITLE
Same as "There is no YAML file in zip you uploaded" 

### ISSUE THREAD

**Issue by songdejia** [SilvioGiancola/TrackingNet-devkit#13]
Hi there, I have seen same issue was closed recently, but no solution. 
Today same problem happens, our result is [https://drive.google.com/file/d/1k3SrTktaJsChygLdraiqM43uJdg2jEmY/view](url).
Thanks in advance.

**Comment by SilvioGiancola** [comment]
Hi, I run your submission on the server without any issue. Could you please send me a screenshot of your error? I guess you are in the same team than the previous issue, since you are getting *exactly* the same results:
```
        Precision 66.4294402491
        NormalizedPrecision 78.844017693
        Success 72.6283813851
```
Are you exceeding your quota of submission? what's your team/user ID? We can connect on [SLACK](https://join.slack.com/t/tracking-net/shared_invite/enQtNTYxNTEyMjYwMTQ0LTEyYmYxM2E5NzViZWRmYTU2ODI4ZGIyYTMwOWRkMDQ0YjljZmQzYmRjNGM4MjVjZTdlN2UwNTg5MDRkOTJhODk) if you want.

**Comment by SilvioGiancola** [comment]
Thanks for your email with the pictures. You don't have to *create* a challenge, but to *participate* to a challenge.

Go to "AI Challenges" -> "TrackingNet" and follow the instructions from there.
