### ISSUE TITLE
How to use proxy for downloading the dataset?

### ISSUE THREAD

**Issue by AlphaGoMK** [SilvioGiancola/TrackingNet-devkit#7]
I got ProxyError due to poor network connection. How to download dataset via proxy mode.  
And it would be much better if Google Drive share link is available :)  

```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='doc-04-30-docs.googleusercontent.com', port=443): Max retries exceeded with url:  
/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/gmr93admk806r7ajo6n5gob9j359l7lh/1551607200000/04760221533142231278/*/1_2fQR73ry85SQojJYKysvG6Z6Daq_AWy (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```

**Comment by SilvioGiancola** [comment]
Hi @AlphaGoMK, unfortunately due to the large number of files, it will be impossible for you to download each single file using a single Google Drive link per file. You can have a look at the csv files provided [here](https://github.com/SilvioGiancola/TrackingNet-devkit/tree/master/csv_link) if you want to access a single TrackingNet file. Those csv files contain all the the Google Drive links called in the downloader script.

Also, providing folders link is impossible since Google Drive zips the folders by default and it fails when it has many files to process.

As a matter of fact, the easiest way is to use the script provided in this repo.

**Comment by asdfqwer2015** [comment]
And why not add a proxy support in download script?
